## Cassandra Operator Image
##
image:
  repository: ghcr.io/cscetbon/casskop
  tag: 2.1.10
  pullPolicy: Always
  imagePullSecrets:
    enabled: false

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 512Mi

readinessProbe:
  timeouts:
    initialDelaySeconds: 4
    periodSeconds: 10
    failureThreshold: 1
livenessProbe:
  timeouts:
    initialDelaySeconds: 4
    periodSeconds: 10
    failureThreshold: 1

## If true, create & deploy the CRD
##
createCustomResource: true

## If true, create & use RBAC resources
##
rbacEnable: true

## If true (and rbacEnable=true), create & use clusterrole and clusterrolebinding
##
rbacCreateClusterRole: true

## if true deploy service for metrics access
metricService: false

debug:
  enabled: false

##
clusterServiceAccountsName:
  - cassandra-cluster-node
