apiVersion: v1
description: A Helm chart for MultiCassKop - the Orange Multiple Cassandra Kubernetes operator
name: multi-casskop-helm
home: &home https://github.com/cscetbon/casskop/multi-casskop
sources:
  - *home
version: &version 1.0.0
appVersion: *version
maintainers:
  - name: cscetbon
    email: cscetbon@gmail.com
  - name: fdehay
    email: franck.dehay@orange.com
keywords:
- operator
- cassandra
- casskop
- multi-casskop
- multi-clusters
